### ISSUE TITLE
How does this work for entities other than Activities?

### ISSUE THREAD

**Issue by petednz** [compucorp/uk.co.compucorp.civicrm.activityreport#80]
In an email Jamie said ... (ignore the name, it supports more then activities)

But when I enable it (and rebuild menus) while i do see an Activity Report entry which now gives the Pivot Table builder, I am unclear how to apply this for non-Activity data.

**Comment by jamienovick** [comment]
@petednz please checkout latest development branch. We've not tagged a new release as we are still fixing bugs so will get it merged to master in the next few weeks. Feel free to test it out in beta (and feel free to report any bugs). We'll also be looking to get it "shoreditch" theme compatible...

**Comment by petednz** [comment]
Ok. seems to answer my question. i can now create Case Pivot Report 'configurations'
